### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by SQLThomas** [Azure-Samples/SQL-db-in-Fabric-Workshop#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Click on any of the links on the first page

### Any log messages given by the failure
> 404 error

### Expected/desired behavior
> Should take you to the respective chapter of the repo.

### OS and Version?
> any

### Versions
>

### Mention any other details that might be useful
Links look like copied over from "akatesmith/SQL-database-in-Fabric-Workshop" repo.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by akatesmith** [comment]
Should be fixed now, I think.
